### ISSUE TITLE
composer require dvizh/yii2-shop "@dev"

### ISSUE THREAD

**Issue by awebc** [dvizh/yii2-shop#4]
composer require dvizh/yii2-shop "@dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dvizh/yii2-shop @dev -> satisfiable by dvizh/yii2-shop[dev-master].
    - dvizh/yii2-shop dev-master requires dvizh/yii2-gallery * -> satisfiable by dvizh/yii2-gallery[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by awebc** [comment]
because my composer.josn :  "minimum-stability": "stable",

**Comment by pistol88** [comment]
yes
all modules are dev

**Comment by awebc** [comment]
I mean: 'dvizh/yii2-gallery @dev ' instead of 'dvizh/yii2-gallery * ' in yii2-shop composer.json
and other your module

**Comment by pistol88** [comment]
Thanks!
